[project]
name = "auto-device-status"
version = "1.0.0"
description = "Automatically mark devices as offline"
authors = [{ name = "Krnl", email = "nt@siiway.org" }]
dependencies = []

[tool.sleepy]
enabled = true
dependencies = []
